#pragma config(Sensor, dgtl1,  button ,        sensorTouch)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port8,           right,         tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		while(SensorValue(button)==1)
		{
			motor[port2]=78;
			motor[port8]=-78;
			//wait1Msec(500);
		}

		motor[left]=0;
		motor[right]=0;
	}



}
