#pragma config(Sensor, dgtl1,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl8,  ultrasonicinput, sensorSONAR_inch)
#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           left,          tmotorVex393_MC29, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		if(SensorValue[dgt18]<=6){
			motor[left]=0;
			motor[right]=0;
		}
		else{

			motor[left]=-60;
			//wait1Msec(500);

			motor[right]=60;
			//wait1Msec(500);
		}
	}

	/*
	while(SensorValue(bumper)==0){

	}
	*/




}
